# Generated by Django 4.2.5 on 2023-11-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Aut', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Cat', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Edi', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=255, unique=True)),
                ('nombre', models.TextField(max_length=255)),
                ('ape_pat', models.TextField(max_length=255)),
                ('ape_mat', models.TextField(max_length=255)),
                ('direccion', models.TextField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('correo', models.TextField(max_length=255)),
                ('nacimiento', models.DateField()),
                ('contraseña', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.TextField(max_length=255)),
                ('Num_Ser', models.IntegerField()),
                ('Publicacion', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.categoria')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.usuario')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteca.libro')),
            ],
        ),
    ]
